//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNet_MBWay_demo.MBWayConnectedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOperation", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ResultOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASPNet_MBWay_demo.MBWayConnectedService.MBWayPaymentOperationResult MBWayPaymentOperationResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASPNet_MBWay_demo.MBWayConnectedService.MBWayPaymentOperationResult MBWayPaymentOperationResult {
            get {
                return this.MBWayPaymentOperationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.MBWayPaymentOperationResultField, value) != true)) {
                    this.MBWayPaymentOperationResultField = value;
                    this.RaisePropertyChanged("MBWayPaymentOperationResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MBWayPaymentOperationResult", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    [System.SerializableAttribute()]
    public partial class MBWayPaymentOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescriptionDetail {
            get {
                return this.StatusDescriptionDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionDetailField, value) != true)) {
                    this.StatusDescriptionDetailField = value;
                    this.RaisePropertyChanged("StatusDescriptionDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDetails", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ResultDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASPNet_MBWay_demo.MBWayConnectedService.MBWayPaymentMerchant MBWayPaymentDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASPNet_MBWay_demo.MBWayConnectedService.MBWayPaymentMerchant MBWayPaymentDetails {
            get {
                return this.MBWayPaymentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MBWayPaymentDetailsField, value) != true)) {
                    this.MBWayPaymentDetailsField = value;
                    this.RaisePropertyChanged("MBWayPaymentDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MBWayPaymentMerchant", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    [System.SerializableAttribute()]
    public partial class MBWayPaymentMerchant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateStatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescriptionDetail {
            get {
                return this.StatusDescriptionDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionDetailField, value) != true)) {
                    this.StatusDescriptionDetailField = value;
                    this.RaisePropertyChanged("StatusDescriptionDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateStatusDate {
            get {
                return this.UpdateStatusDateField;
            }
            set {
                if ((this.UpdateStatusDateField.Equals(value) != true)) {
                    this.UpdateStatusDateField = value;
                    this.RaisePropertyChanged("UpdateStatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidRequest {
            get {
                return this.ValidRequestField;
            }
            set {
                if ((this.ValidRequestField.Equals(value) != true)) {
                    this.ValidRequestField = value;
                    this.RaisePropertyChanged("ValidRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultRequestRefund", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ResultRequestRefund : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRefundDetails", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class RequestRefundDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASPNet_MBWay_demo.MBWayConnectedService.MBWayRefundRequestMerchant RefundDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASPNet_MBWay_demo.MBWayConnectedService.MBWayRefundRequestMerchant RefundDetails {
            get {
                return this.RefundDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundDetailsField, value) != true)) {
                    this.RefundDetailsField = value;
                    this.RaisePropertyChanged("RefundDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MBWayRefundRequestMerchant", Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    [System.SerializableAttribute()]
    public partial class MBWayRefundRequestMerchant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CFEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CFMerchantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ProcessedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CFEntity {
            get {
                return this.CFEntityField;
            }
            set {
                if ((this.CFEntityField.Equals(value) != true)) {
                    this.CFEntityField = value;
                    this.RaisePropertyChanged("CFEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CFMerchantId {
            get {
                return this.CFMerchantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CFMerchantIdField, value) != true)) {
                    this.CFMerchantIdField = value;
                    this.RaisePropertyChanged("CFMerchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientEmail {
            get {
                return this.ClientEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientEmailField, value) != true)) {
                    this.ClientEmailField = value;
                    this.RaisePropertyChanged("ClientEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProcessedDate {
            get {
                return this.ProcessedDateField;
            }
            set {
                if ((this.ProcessedDateField.Equals(value) != true)) {
                    this.ProcessedDateField = value;
                    this.RaisePropertyChanged("ProcessedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MBWayConnectedService.IMBWayWebServiceV2")]
    public interface IMBWayWebServiceV2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/CreatePayment", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/CreatePaymentResponse")]
        ASPNet_MBWay_demo.MBWayConnectedService.ResultOperation CreatePayment(string cfMerchantId, string password, int cfEntityOrType, decimal amount, string phone, string description, string clientEmail, string clientVATNumber, string clientExternalReference, string clientName, int categoryId, string callBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/CreatePayment", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/CreatePaymentResponse")]
        System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultOperation> CreatePaymentAsync(string cfMerchantId, string password, int cfEntityOrType, decimal amount, string phone, string description, string clientEmail, string clientVATNumber, string clientExternalReference, string clientName, int categoryId, string callBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetailsResponse")]
        ASPNet_MBWay_demo.MBWayConnectedService.ResultDetails GetPaymentDetails(string cfMerchantId, string password, int cfEntityOrType, string operationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetailsResponse")]
        System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultDetails> GetPaymentDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/RequestRefund", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/RequestRefundResponse")]
        ASPNet_MBWay_demo.MBWayConnectedService.ResultRequestRefund RequestRefund(string cfMerchantId, string password, int cfEntityOrType, string operationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/RequestRefund", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/RequestRefundResponse")]
        System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultRequestRefund> RequestRefundAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetailsResponse")]
        ASPNet_MBWay_demo.MBWayConnectedService.RequestRefundDetails GetRequestRefundDetails(string cfMerchantId, string password, int cfEntityOrType, string operationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", ReplyAction="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetailsResponse")]
        System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.RequestRefundDetails> GetRequestRefundDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMBWayWebServiceV2Channel : ASPNet_MBWay_demo.MBWayConnectedService.IMBWayWebServiceV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MBWayWebServiceV2Client : System.ServiceModel.ClientBase<ASPNet_MBWay_demo.MBWayConnectedService.IMBWayWebServiceV2>, ASPNet_MBWay_demo.MBWayConnectedService.IMBWayWebServiceV2 {
        
        public MBWayWebServiceV2Client() {
        }
        
        public MBWayWebServiceV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MBWayWebServiceV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBWayWebServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBWayWebServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ASPNet_MBWay_demo.MBWayConnectedService.ResultOperation CreatePayment(string cfMerchantId, string password, int cfEntityOrType, decimal amount, string phone, string description, string clientEmail, string clientVATNumber, string clientExternalReference, string clientName, int categoryId, string callBackURL) {
            return base.Channel.CreatePayment(cfMerchantId, password, cfEntityOrType, amount, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, callBackURL);
        }
        
        public System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultOperation> CreatePaymentAsync(string cfMerchantId, string password, int cfEntityOrType, decimal amount, string phone, string description, string clientEmail, string clientVATNumber, string clientExternalReference, string clientName, int categoryId, string callBackURL) {
            return base.Channel.CreatePaymentAsync(cfMerchantId, password, cfEntityOrType, amount, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, callBackURL);
        }
        
        public ASPNet_MBWay_demo.MBWayConnectedService.ResultDetails GetPaymentDetails(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.GetPaymentDetails(cfMerchantId, password, cfEntityOrType, operationId);
        }
        
        public System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultDetails> GetPaymentDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.GetPaymentDetailsAsync(cfMerchantId, password, cfEntityOrType, operationId);
        }
        
        public ASPNet_MBWay_demo.MBWayConnectedService.ResultRequestRefund RequestRefund(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.RequestRefund(cfMerchantId, password, cfEntityOrType, operationId);
        }
        
        public System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.ResultRequestRefund> RequestRefundAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.RequestRefundAsync(cfMerchantId, password, cfEntityOrType, operationId);
        }
        
        public ASPNet_MBWay_demo.MBWayConnectedService.RequestRefundDetails GetRequestRefundDetails(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.GetRequestRefundDetails(cfMerchantId, password, cfEntityOrType, operationId);
        }
        
        public System.Threading.Tasks.Task<ASPNet_MBWay_demo.MBWayConnectedService.RequestRefundDetails> GetRequestRefundDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, string operationId) {
            return base.Channel.GetRequestRefundDetailsAsync(cfMerchantId, password, cfEntityOrType, operationId);
        }
    }
}
