//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASPNet_MBWay_demo.MBWayService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMBWayWebServiceV2", Namespace="http://tempuri.org/")]
    public partial class MBWayWebServiceV2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreatePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequestRefundDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MBWayWebServiceV2() {
            this.Url = global::ASPNet_MBWay_demo.Properties.Settings.Default.ASPNet_MBWay_demo_MBWayService_MBWayWebServiceV2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreatePaymentCompletedEventHandler CreatePaymentCompleted;
        
        /// <remarks/>
        public event GetPaymentDetailsCompletedEventHandler GetPaymentDetailsCompleted;
        
        /// <remarks/>
        public event RequestRefundCompletedEventHandler RequestRefundCompleted;
        
        /// <remarks/>
        public event GetRequestRefundDetailsCompletedEventHandler GetRequestRefundDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/CreatePayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultOperation CreatePayment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfMerchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, int cfEntityOrType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cfEntityOrTypeSpecified, decimal amount, [System.Xml.Serialization.XmlIgnoreAttribute()] bool amountSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string description, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientEmail, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientVATNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientExternalReference, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientName, int categoryId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool categoryIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string callBackURL) {
            object[] results = this.Invoke("CreatePayment", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        amount,
                        amountSpecified,
                        phone,
                        description,
                        clientEmail,
                        clientVATNumber,
                        clientExternalReference,
                        clientName,
                        categoryId,
                        categoryIdSpecified,
                        callBackURL});
            return ((ResultOperation)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePaymentAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, decimal amount, bool amountSpecified, string phone, string description, string clientEmail, string clientVATNumber, string clientExternalReference, string clientName, int categoryId, bool categoryIdSpecified, string callBackURL) {
            this.CreatePaymentAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, amount, amountSpecified, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, categoryIdSpecified, callBackURL, null);
        }
        
        /// <remarks/>
        public void CreatePaymentAsync(
                    string cfMerchantId, 
                    string password, 
                    int cfEntityOrType, 
                    bool cfEntityOrTypeSpecified, 
                    decimal amount, 
                    bool amountSpecified, 
                    string phone, 
                    string description, 
                    string clientEmail, 
                    string clientVATNumber, 
                    string clientExternalReference, 
                    string clientName, 
                    int categoryId, 
                    bool categoryIdSpecified, 
                    string callBackURL, 
                    object userState) {
            if ((this.CreatePaymentOperationCompleted == null)) {
                this.CreatePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePaymentOperationCompleted);
            }
            this.InvokeAsync("CreatePayment", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        amount,
                        amountSpecified,
                        phone,
                        description,
                        clientEmail,
                        clientVATNumber,
                        clientExternalReference,
                        clientName,
                        categoryId,
                        categoryIdSpecified,
                        callBackURL}, this.CreatePaymentOperationCompleted, userState);
        }
        
        private void OnCreatePaymentOperationCompleted(object arg) {
            if ((this.CreatePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePaymentCompleted(this, new CreatePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultDetails GetPaymentDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfMerchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, int cfEntityOrType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cfEntityOrTypeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string operationId) {
            object[] results = this.Invoke("GetPaymentDetails", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId});
            return ((ResultDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId) {
            this.GetPaymentDetailsAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, null);
        }
        
        /// <remarks/>
        public void GetPaymentDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId, object userState) {
            if ((this.GetPaymentDetailsOperationCompleted == null)) {
                this.GetPaymentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentDetailsOperationCompleted);
            }
            this.InvokeAsync("GetPaymentDetails", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId}, this.GetPaymentDetailsOperationCompleted, userState);
        }
        
        private void OnGetPaymentDetailsOperationCompleted(object arg) {
            if ((this.GetPaymentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentDetailsCompleted(this, new GetPaymentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/RequestRefund", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultRequestRefund RequestRefund([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfMerchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, int cfEntityOrType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cfEntityOrTypeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string operationId) {
            object[] results = this.Invoke("RequestRefund", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId});
            return ((ResultRequestRefund)(results[0]));
        }
        
        /// <remarks/>
        public void RequestRefundAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId) {
            this.RequestRefundAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, null);
        }
        
        /// <remarks/>
        public void RequestRefundAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId, object userState) {
            if ((this.RequestRefundOperationCompleted == null)) {
                this.RequestRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestRefundOperationCompleted);
            }
            this.InvokeAsync("RequestRefund", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId}, this.RequestRefundOperationCompleted, userState);
        }
        
        private void OnRequestRefundOperationCompleted(object arg) {
            if ((this.RequestRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestRefundCompleted(this, new RequestRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RequestRefundDetails GetRequestRefundDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfMerchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, int cfEntityOrType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cfEntityOrTypeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string operationId) {
            object[] results = this.Invoke("GetRequestRefundDetails", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId});
            return ((RequestRefundDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetRequestRefundDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId) {
            this.GetRequestRefundDetailsAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, null);
        }
        
        /// <remarks/>
        public void GetRequestRefundDetailsAsync(string cfMerchantId, string password, int cfEntityOrType, bool cfEntityOrTypeSpecified, string operationId, object userState) {
            if ((this.GetRequestRefundDetailsOperationCompleted == null)) {
                this.GetRequestRefundDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequestRefundDetailsOperationCompleted);
            }
            this.InvokeAsync("GetRequestRefundDetails", new object[] {
                        cfMerchantId,
                        password,
                        cfEntityOrType,
                        cfEntityOrTypeSpecified,
                        operationId}, this.GetRequestRefundDetailsOperationCompleted, userState);
        }
        
        private void OnGetRequestRefundDetailsOperationCompleted(object arg) {
            if ((this.GetRequestRefundDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequestRefundDetailsCompleted(this, new GetRequestRefundDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    public partial class ResultOperation {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private MBWayPaymentOperationResult mBWayPaymentOperationResultField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MBWayPaymentOperationResult MBWayPaymentOperationResult {
            get {
                return this.mBWayPaymentOperationResultField;
            }
            set {
                this.mBWayPaymentOperationResultField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    public partial class MBWayPaymentOperationResult {
        
        private string operationIdField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string statusDescriptionDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescriptionDetail {
            get {
                return this.statusDescriptionDetailField;
            }
            set {
                this.statusDescriptionDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    public partial class MBWayRefundRequestMerchant {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private int cFEntityField;
        
        private bool cFEntityFieldSpecified;
        
        private string cFMerchantIdField;
        
        private string clientEmailField;
        
        private string operationIdField;
        
        private string phoneField;
        
        private System.Nullable<System.DateTime> processedDateField;
        
        private bool processedDateFieldSpecified;
        
        private System.Nullable<System.DateTime> requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private string sourceField;
        
        private string statusField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CFEntity {
            get {
                return this.cFEntityField;
            }
            set {
                this.cFEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CFEntitySpecified {
            get {
                return this.cFEntityFieldSpecified;
            }
            set {
                this.cFEntityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CFMerchantId {
            get {
                return this.cFMerchantIdField;
            }
            set {
                this.cFMerchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientEmail {
            get {
                return this.clientEmailField;
            }
            set {
                this.clientEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ProcessedDate {
            get {
                return this.processedDateField;
            }
            set {
                this.processedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessedDateSpecified {
            get {
                return this.processedDateFieldSpecified;
            }
            set {
                this.processedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestDateSpecified {
            get {
                return this.requestDateFieldSpecified;
            }
            set {
                this.requestDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    public partial class RequestRefundDetails {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private MBWayRefundRequestMerchant refundDetailsField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MBWayRefundRequestMerchant RefundDetails {
            get {
                return this.refundDetailsField;
            }
            set {
                this.refundDetailsField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    public partial class ResultRequestRefund {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")]
    public partial class MBWayPaymentMerchant {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private string descriptionField;
        
        private string operationIdField;
        
        private string phoneField;
        
        private System.Nullable<System.DateTime> requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string statusDescriptionDetailField;
        
        private System.Nullable<System.DateTime> updateStatusDateField;
        
        private bool updateStatusDateFieldSpecified;
        
        private bool validRequestField;
        
        private bool validRequestFieldSpecified;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified {
            get {
                return this.categoryIdFieldSpecified;
            }
            set {
                this.categoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestDateSpecified {
            get {
                return this.requestDateFieldSpecified;
            }
            set {
                this.requestDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescriptionDetail {
            get {
                return this.statusDescriptionDetailField;
            }
            set {
                this.statusDescriptionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateStatusDate {
            get {
                return this.updateStatusDateField;
            }
            set {
                this.updateStatusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateStatusDateSpecified {
            get {
                return this.updateStatusDateFieldSpecified;
            }
            set {
                this.updateStatusDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ValidRequest {
            get {
                return this.validRequestField;
            }
            set {
                this.validRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidRequestSpecified {
            get {
                return this.validRequestFieldSpecified;
            }
            set {
                this.validRequestFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti" +
        "es")]
    public partial class ResultDetails {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private MBWayPaymentMerchant mBWayPaymentDetailsField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MBWayPaymentMerchant MBWayPaymentDetails {
            get {
                return this.mBWayPaymentDetailsField;
            }
            set {
                this.mBWayPaymentDetailsField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreatePaymentCompletedEventHandler(object sender, CreatePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultOperation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultOperation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPaymentDetailsCompletedEventHandler(object sender, GetPaymentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestRefundCompletedEventHandler(object sender, RequestRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultRequestRefund Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultRequestRefund)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRequestRefundDetailsCompletedEventHandler(object sender, GetRequestRefundDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequestRefundDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequestRefundDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestRefundDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestRefundDetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591