//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompraFacilWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.comprafacil.pt/", ConfigurationName="CompraFacilWS.CompraFacilWSSoap")]
    public interface CompraFacilWSSoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/GetReferencesInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.GetReferencesInfo1> getInfoAsync(CompraFacilWS.GetReferencesInfo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/getInfoReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.getInfoReferenceResponse> getInfoReferenceAsync(CompraFacilWS.getInfoReferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/getReferenceMB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.getReferenceMBResponse> getReferenceMBAsync(CompraFacilWS.getReferenceMBRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/getReferenceMB2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.getReferenceMB2Response> getReferenceMB2Async(CompraFacilWS.getReferenceMB2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/getReferencePS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.getReferencePSResponse> getReferencePSAsync(CompraFacilWS.getReferencePSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comprafacil.pt/getReferencePS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompraFacilWS.getReferencePS2Response> getReferencePS2Async(CompraFacilWS.getReferencePS2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReferencesInfo", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class GetReferencesInfo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string dateStartStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public string dataEndStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string type;
        
        public GetReferencesInfo()
        {
        }
        
        public GetReferencesInfo(string username, string password, string dateStartStr, string dataEndStr, string type)
        {
            this.username = username;
            this.password = password;
            this.dateStartStr = dateStartStr;
            this.dataEndStr = dataEndStr;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReferencesInfoResponse", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class GetReferencesInfo1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool GetReferencesInfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string referencesList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string IDsList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public string error;
        
        public GetReferencesInfo1()
        {
        }
        
        public GetReferencesInfo1(bool GetReferencesInfoResult, string referencesList, string IDsList, string error)
        {
            this.GetReferencesInfoResult = GetReferencesInfoResult;
            this.referencesList = referencesList;
            this.IDsList = IDsList;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoReference", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getInfoReferenceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string password;
        
        public getInfoReferenceRequest()
        {
        }
        
        public getInfoReferenceRequest(string reference, string username, string password)
        {
            this.reference = reference;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoReferenceResponse", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getInfoReferenceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool getInfoReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public bool paid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public string lastPaymentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public int totalPayments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=5)]
        public string error;
        
        public getInfoReferenceResponse()
        {
        }
        
        public getInfoReferenceResponse(bool getInfoReferenceResult, bool paid, string status, string lastPaymentDate, int totalPayments, string error)
        {
            this.getInfoReferenceResult = getInfoReferenceResult;
            this.paid = paid;
            this.status = status;
            this.lastPaymentDate = lastPaymentDate;
            this.totalPayments = totalPayments;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferenceMB", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferenceMBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string additionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=5)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=6)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=7)]
        public string postCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=8)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=9)]
        public string NIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=10)]
        public string externalReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=11)]
        public string contactPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=12)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=13)]
        public int IDUserBackoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=14)]
        public int timeLimitDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=15)]
        public bool sendEmailBuyer;
        
        public getReferenceMBRequest()
        {
        }
        
        public getReferenceMBRequest(
                    string origin, 
                    string username, 
                    string password, 
                    decimal amount, 
                    string additionalInfo, 
                    string name, 
                    string address, 
                    string postCode, 
                    string city, 
                    string NIC, 
                    string externalReference, 
                    string contactPhone, 
                    string email, 
                    int IDUserBackoffice, 
                    int timeLimitDays, 
                    bool sendEmailBuyer)
        {
            this.origin = origin;
            this.username = username;
            this.password = password;
            this.amount = amount;
            this.additionalInfo = additionalInfo;
            this.name = name;
            this.address = address;
            this.postCode = postCode;
            this.city = city;
            this.NIC = NIC;
            this.externalReference = externalReference;
            this.contactPhone = contactPhone;
            this.email = email;
            this.IDUserBackoffice = IDUserBackoffice;
            this.timeLimitDays = timeLimitDays;
            this.sendEmailBuyer = sendEmailBuyer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferenceMBResponse", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferenceMBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool getReferenceMBResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string entity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal amountOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string error;
        
        public getReferenceMBResponse()
        {
        }
        
        public getReferenceMBResponse(bool getReferenceMBResult, string reference, string entity, decimal amountOut, string error)
        {
            this.getReferenceMBResult = getReferenceMBResult;
            this.reference = reference;
            this.entity = entity;
            this.amountOut = amountOut;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferenceMB2", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferenceMB2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string productID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public int quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=5)]
        public string additionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=6)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=7)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=8)]
        public string postCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=9)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=10)]
        public string NIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=11)]
        public string externalReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=12)]
        public string contactPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=13)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=14)]
        public int IDUserBackoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=15)]
        public int timeLimitDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=16)]
        public bool sendEmailBuyer;
        
        public getReferenceMB2Request()
        {
        }
        
        public getReferenceMB2Request(
                    string origin, 
                    string productID, 
                    string username, 
                    string password, 
                    int quantity, 
                    string additionalInfo, 
                    string name, 
                    string address, 
                    string postCode, 
                    string city, 
                    string NIC, 
                    string externalReference, 
                    string contactPhone, 
                    string email, 
                    int IDUserBackoffice, 
                    int timeLimitDays, 
                    bool sendEmailBuyer)
        {
            this.origin = origin;
            this.productID = productID;
            this.username = username;
            this.password = password;
            this.quantity = quantity;
            this.additionalInfo = additionalInfo;
            this.name = name;
            this.address = address;
            this.postCode = postCode;
            this.city = city;
            this.NIC = NIC;
            this.externalReference = externalReference;
            this.contactPhone = contactPhone;
            this.email = email;
            this.IDUserBackoffice = IDUserBackoffice;
            this.timeLimitDays = timeLimitDays;
            this.sendEmailBuyer = sendEmailBuyer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferenceMB2Response", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferenceMB2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool getReferenceMB2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string entity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal amountOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string error;
        
        public getReferenceMB2Response()
        {
        }
        
        public getReferenceMB2Response(bool getReferenceMB2Result, string reference, string entity, decimal amountOut, string error)
        {
            this.getReferenceMB2Result = getReferenceMB2Result;
            this.reference = reference;
            this.entity = entity;
            this.amountOut = amountOut;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferencePS", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferencePSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string additionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=5)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=6)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=7)]
        public string postCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=8)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=9)]
        public string NIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=10)]
        public string externalReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=11)]
        public string contactPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=12)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=13)]
        public int IDUserBackoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=14)]
        public bool sendEmailBuyer;
        
        public getReferencePSRequest()
        {
        }
        
        public getReferencePSRequest(string origin, string username, string password, decimal amount, string additionalInfo, string name, string address, string postCode, string city, string NIC, string externalReference, string contactPhone, string email, int IDUserBackoffice, bool sendEmailBuyer)
        {
            this.origin = origin;
            this.username = username;
            this.password = password;
            this.amount = amount;
            this.additionalInfo = additionalInfo;
            this.name = name;
            this.address = address;
            this.postCode = postCode;
            this.city = city;
            this.NIC = NIC;
            this.externalReference = externalReference;
            this.contactPhone = contactPhone;
            this.email = email;
            this.IDUserBackoffice = IDUserBackoffice;
            this.sendEmailBuyer = sendEmailBuyer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferencePSResponse", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferencePSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool getReferencePSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string paymentDeadline;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal amountOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string error;
        
        public getReferencePSResponse()
        {
        }
        
        public getReferencePSResponse(bool getReferencePSResult, string reference, string paymentDeadline, decimal amountOut, string error)
        {
            this.getReferencePSResult = getReferencePSResult;
            this.reference = reference;
            this.paymentDeadline = paymentDeadline;
            this.amountOut = amountOut;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferencePS2", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferencePS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string productID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public int quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=5)]
        public string additionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=6)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=7)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=8)]
        public string postCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=9)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=10)]
        public string NIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=11)]
        public string externalReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=12)]
        public string contactPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=13)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=14)]
        public int IDUserBackoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=15)]
        public bool sendEmailBuyer;
        
        public getReferencePS2Request()
        {
        }
        
        public getReferencePS2Request(
                    string origin, 
                    string productID, 
                    string username, 
                    string password, 
                    int quantity, 
                    string additionalInfo, 
                    string name, 
                    string address, 
                    string postCode, 
                    string city, 
                    string NIC, 
                    string externalReference, 
                    string contactPhone, 
                    string email, 
                    int IDUserBackoffice, 
                    bool sendEmailBuyer)
        {
            this.origin = origin;
            this.productID = productID;
            this.username = username;
            this.password = password;
            this.quantity = quantity;
            this.additionalInfo = additionalInfo;
            this.name = name;
            this.address = address;
            this.postCode = postCode;
            this.city = city;
            this.NIC = NIC;
            this.externalReference = externalReference;
            this.contactPhone = contactPhone;
            this.email = email;
            this.IDUserBackoffice = IDUserBackoffice;
            this.sendEmailBuyer = sendEmailBuyer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReferencePS2Response", WrapperNamespace="http://www.comprafacil.pt/", IsWrapped=true)]
    public partial class getReferencePS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=0)]
        public bool getReferencePS2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=1)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=2)]
        public string paymentDeadline;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=3)]
        public decimal valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.comprafacil.pt/", Order=4)]
        public string error;
        
        public getReferencePS2Response()
        {
        }
        
        public getReferencePS2Response(bool getReferencePS2Result, string reference, string paymentDeadline, decimal valor, string error)
        {
            this.getReferencePS2Result = getReferencePS2Result;
            this.reference = reference;
            this.paymentDeadline = paymentDeadline;
            this.valor = valor;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface CompraFacilWSSoapChannel : CompraFacilWS.CompraFacilWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CompraFacilWSSoapClient : System.ServiceModel.ClientBase<CompraFacilWS.CompraFacilWSSoap>, CompraFacilWS.CompraFacilWSSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompraFacilWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CompraFacilWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CompraFacilWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraFacilWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompraFacilWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraFacilWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompraFacilWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraFacilWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.GetReferencesInfo1> getInfoAsync(CompraFacilWS.GetReferencesInfo request)
        {
            return base.Channel.getInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.getInfoReferenceResponse> getInfoReferenceAsync(CompraFacilWS.getInfoReferenceRequest request)
        {
            return base.Channel.getInfoReferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.getReferenceMBResponse> getReferenceMBAsync(CompraFacilWS.getReferenceMBRequest request)
        {
            return base.Channel.getReferenceMBAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.getReferenceMB2Response> getReferenceMB2Async(CompraFacilWS.getReferenceMB2Request request)
        {
            return base.Channel.getReferenceMB2Async(request);
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.getReferencePSResponse> getReferencePSAsync(CompraFacilWS.getReferencePSRequest request)
        {
            return base.Channel.getReferencePSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompraFacilWS.getReferencePS2Response> getReferencePS2Async(CompraFacilWS.getReferencePS2Request request)
        {
            return base.Channel.getReferencePS2Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompraFacilWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CompraFacilWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompraFacilWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://comprafacil2.hipay.pt/webservice/CompraFacilWs.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CompraFacilWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://comprafacil2.hipay.pt/webservice/CompraFacilWs.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CompraFacilWSSoap,
            
            CompraFacilWSSoap12,
        }
    }
}
