'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace MBWayService
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IMBWayWebServiceV2", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MBWayWebServiceV2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreatePaymentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPaymentDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RequestRefundOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRequestRefundDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ASPNet_MBWay_demoVB.My.MySettings.Default.ASPNet_MBWay_demoVB_MBWayService_MBWayWebServiceV2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreatePaymentCompleted As CreatePaymentCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPaymentDetailsCompleted As GetPaymentDetailsCompletedEventHandler
        
        '''<remarks/>
        Public Event RequestRefundCompleted As RequestRefundCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRequestRefundDetailsCompleted As GetRequestRefundDetailsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/CreatePayment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreatePayment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal cfMerchantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal cfEntityOrType As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal cfEntityOrTypeSpecified As Boolean, ByVal amount As Decimal, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal amountSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal phone As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal description As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clientEmail As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clientVATNumber As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clientExternalReference As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clientName As String, ByVal categoryId As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal categoryIdSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal callBackURL As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ResultOperation
            Dim results() As Object = Me.Invoke("CreatePayment", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, amount, amountSpecified, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, categoryIdSpecified, callBackURL})
            Return CType(results(0),ResultOperation)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreatePaymentAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal amount As Decimal, ByVal amountSpecified As Boolean, ByVal phone As String, ByVal description As String, ByVal clientEmail As String, ByVal clientVATNumber As String, ByVal clientExternalReference As String, ByVal clientName As String, ByVal categoryId As Integer, ByVal categoryIdSpecified As Boolean, ByVal callBackURL As String)
            Me.CreatePaymentAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, amount, amountSpecified, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, categoryIdSpecified, callBackURL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreatePaymentAsync( _
                    ByVal cfMerchantId As String,  _
                    ByVal password As String,  _
                    ByVal cfEntityOrType As Integer,  _
                    ByVal cfEntityOrTypeSpecified As Boolean,  _
                    ByVal amount As Decimal,  _
                    ByVal amountSpecified As Boolean,  _
                    ByVal phone As String,  _
                    ByVal description As String,  _
                    ByVal clientEmail As String,  _
                    ByVal clientVATNumber As String,  _
                    ByVal clientExternalReference As String,  _
                    ByVal clientName As String,  _
                    ByVal categoryId As Integer,  _
                    ByVal categoryIdSpecified As Boolean,  _
                    ByVal callBackURL As String,  _
                    ByVal userState As Object)
            If (Me.CreatePaymentOperationCompleted Is Nothing) Then
                Me.CreatePaymentOperationCompleted = AddressOf Me.OnCreatePaymentOperationCompleted
            End If
            Me.InvokeAsync("CreatePayment", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, amount, amountSpecified, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, categoryIdSpecified, callBackURL}, Me.CreatePaymentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreatePaymentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreatePaymentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreatePaymentCompleted(Me, New CreatePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPaymentDetails(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal cfMerchantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal cfEntityOrType As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal cfEntityOrTypeSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operationId As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ResultDetails
            Dim results() As Object = Me.Invoke("GetPaymentDetails", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId})
            Return CType(results(0),ResultDetails)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPaymentDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String)
            Me.GetPaymentDetailsAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPaymentDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String, ByVal userState As Object)
            If (Me.GetPaymentDetailsOperationCompleted Is Nothing) Then
                Me.GetPaymentDetailsOperationCompleted = AddressOf Me.OnGetPaymentDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetPaymentDetails", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId}, Me.GetPaymentDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPaymentDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPaymentDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPaymentDetailsCompleted(Me, New GetPaymentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/RequestRefund", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestRefund(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal cfMerchantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal cfEntityOrType As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal cfEntityOrTypeSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operationId As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ResultRequestRefund
            Dim results() As Object = Me.Invoke("RequestRefund", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId})
            Return CType(results(0),ResultRequestRefund)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestRefundAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String)
            Me.RequestRefundAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestRefundAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String, ByVal userState As Object)
            If (Me.RequestRefundOperationCompleted Is Nothing) Then
                Me.RequestRefundOperationCompleted = AddressOf Me.OnRequestRefundOperationCompleted
            End If
            Me.InvokeAsync("RequestRefund", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId}, Me.RequestRefundOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestRefundOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestRefundCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestRefundCompleted(Me, New RequestRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRequestRefundDetails(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal cfMerchantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal cfEntityOrType As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal cfEntityOrTypeSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operationId As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> RequestRefundDetails
            Dim results() As Object = Me.Invoke("GetRequestRefundDetails", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId})
            Return CType(results(0),RequestRefundDetails)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRequestRefundDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String)
            Me.GetRequestRefundDetailsAsync(cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRequestRefundDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal cfEntityOrTypeSpecified As Boolean, ByVal operationId As String, ByVal userState As Object)
            If (Me.GetRequestRefundDetailsOperationCompleted Is Nothing) Then
                Me.GetRequestRefundDetailsOperationCompleted = AddressOf Me.OnGetRequestRefundDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetRequestRefundDetails", New Object() {cfMerchantId, password, cfEntityOrType, cfEntityOrTypeSpecified, operationId}, Me.GetRequestRefundDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRequestRefundDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRequestRefundDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRequestRefundDetailsCompleted(Me, New GetRequestRefundDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es")>  _
    Partial Public Class ResultOperation
        
        Private errorCodeField As Integer
        
        Private errorCodeFieldSpecified As Boolean
        
        Private errorDescriptionField As String
        
        Private mBWayPaymentOperationResultField As MBWayPaymentOperationResult
        
        Private successField As Boolean
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ErrorCodeSpecified() As Boolean
            Get
                Return Me.errorCodeFieldSpecified
            End Get
            Set
                Me.errorCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MBWayPaymentOperationResult() As MBWayPaymentOperationResult
            Get
                Return Me.mBWayPaymentOperationResultField
            End Get
            Set
                Me.mBWayPaymentOperationResultField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")>  _
    Partial Public Class MBWayPaymentOperationResult
        
        Private operationIdField As String
        
        Private statusCodeField As String
        
        Private statusDescriptionField As String
        
        Private statusDescriptionDetailField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OperationId() As String
            Get
                Return Me.operationIdField
            End Get
            Set
                Me.operationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescription() As String
            Get
                Return Me.statusDescriptionField
            End Get
            Set
                Me.statusDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescriptionDetail() As String
            Get
                Return Me.statusDescriptionDetailField
            End Get
            Set
                Me.statusDescriptionDetailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")>  _
    Partial Public Class MBWayRefundRequestMerchant
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private cFEntityField As Integer
        
        Private cFEntityFieldSpecified As Boolean
        
        Private cFMerchantIdField As String
        
        Private clientEmailField As String
        
        Private operationIdField As String
        
        Private phoneField As String
        
        Private processedDateField As System.Nullable(Of Date)
        
        Private processedDateFieldSpecified As Boolean
        
        Private requestDateField As System.Nullable(Of Date)
        
        Private requestDateFieldSpecified As Boolean
        
        Private sourceField As String
        
        Private statusField As String
        
        Private statusDescriptionField As String
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CFEntity() As Integer
            Get
                Return Me.cFEntityField
            End Get
            Set
                Me.cFEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CFEntitySpecified() As Boolean
            Get
                Return Me.cFEntityFieldSpecified
            End Get
            Set
                Me.cFEntityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CFMerchantId() As String
            Get
                Return Me.cFMerchantIdField
            End Get
            Set
                Me.cFMerchantIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ClientEmail() As String
            Get
                Return Me.clientEmailField
            End Get
            Set
                Me.clientEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OperationId() As String
            Get
                Return Me.operationIdField
            End Get
            Set
                Me.operationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProcessedDate() As System.Nullable(Of Date)
            Get
                Return Me.processedDateField
            End Get
            Set
                Me.processedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ProcessedDateSpecified() As Boolean
            Get
                Return Me.processedDateFieldSpecified
            End Get
            Set
                Me.processedDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RequestDate() As System.Nullable(Of Date)
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RequestDateSpecified() As Boolean
            Get
                Return Me.requestDateFieldSpecified
            End Get
            Set
                Me.requestDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescription() As String
            Get
                Return Me.statusDescriptionField
            End Get
            Set
                Me.statusDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es")>  _
    Partial Public Class RequestRefundDetails
        
        Private errorCodeField As Integer
        
        Private errorCodeFieldSpecified As Boolean
        
        Private errorDescriptionField As String
        
        Private refundDetailsField As MBWayRefundRequestMerchant
        
        Private successField As Boolean
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ErrorCodeSpecified() As Boolean
            Get
                Return Me.errorCodeFieldSpecified
            End Get
            Set
                Me.errorCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RefundDetails() As MBWayRefundRequestMerchant
            Get
                Return Me.refundDetailsField
            End Get
            Set
                Me.refundDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es")>  _
    Partial Public Class ResultRequestRefund
        
        Private errorCodeField As Integer
        
        Private errorCodeFieldSpecified As Boolean
        
        Private errorDescriptionField As String
        
        Private successField As Boolean
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ErrorCodeSpecified() As Boolean
            Get
                Return Me.errorCodeFieldSpecified
            End Get
            Set
                Me.errorCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities")>  _
    Partial Public Class MBWayPaymentMerchant
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private categoryIdField As Integer
        
        Private categoryIdFieldSpecified As Boolean
        
        Private descriptionField As String
        
        Private operationIdField As String
        
        Private phoneField As String
        
        Private requestDateField As System.Nullable(Of Date)
        
        Private requestDateFieldSpecified As Boolean
        
        Private statusCodeField As String
        
        Private statusDescriptionField As String
        
        Private statusDescriptionDetailField As String
        
        Private updateStatusDateField As System.Nullable(Of Date)
        
        Private updateStatusDateFieldSpecified As Boolean
        
        Private validRequestField As Boolean
        
        Private validRequestFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CategoryId() As Integer
            Get
                Return Me.categoryIdField
            End Get
            Set
                Me.categoryIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CategoryIdSpecified() As Boolean
            Get
                Return Me.categoryIdFieldSpecified
            End Get
            Set
                Me.categoryIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OperationId() As String
            Get
                Return Me.operationIdField
            End Get
            Set
                Me.operationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RequestDate() As System.Nullable(Of Date)
            Get
                Return Me.requestDateField
            End Get
            Set
                Me.requestDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RequestDateSpecified() As Boolean
            Get
                Return Me.requestDateFieldSpecified
            End Get
            Set
                Me.requestDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescription() As String
            Get
                Return Me.statusDescriptionField
            End Get
            Set
                Me.statusDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescriptionDetail() As String
            Get
                Return Me.statusDescriptionDetailField
            End Get
            Set
                Me.statusDescriptionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UpdateStatusDate() As System.Nullable(Of Date)
            Get
                Return Me.updateStatusDateField
            End Get
            Set
                Me.updateStatusDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property UpdateStatusDateSpecified() As Boolean
            Get
                Return Me.updateStatusDateFieldSpecified
            End Get
            Set
                Me.updateStatusDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidRequest() As Boolean
            Get
                Return Me.validRequestField
            End Get
            Set
                Me.validRequestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ValidRequestSpecified() As Boolean
            Get
                Return Me.validRequestFieldSpecified
            End Get
            Set
                Me.validRequestFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es")>  _
    Partial Public Class ResultDetails
        
        Private errorCodeField As Integer
        
        Private errorCodeFieldSpecified As Boolean
        
        Private errorDescriptionField As String
        
        Private mBWayPaymentDetailsField As MBWayPaymentMerchant
        
        Private successField As Boolean
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ErrorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ErrorCodeSpecified() As Boolean
            Get
                Return Me.errorCodeFieldSpecified
            End Get
            Set
                Me.errorCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MBWayPaymentDetails() As MBWayPaymentMerchant
            Get
                Return Me.mBWayPaymentDetailsField
            End Get
            Set
                Me.mBWayPaymentDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub CreatePaymentCompletedEventHandler(ByVal sender As Object, ByVal e As CreatePaymentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreatePaymentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultOperation
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultOperation)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetPaymentDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetPaymentDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPaymentDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultDetails
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultDetails)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub RequestRefundCompletedEventHandler(ByVal sender As Object, ByVal e As RequestRefundCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestRefundCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultRequestRefund
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultRequestRefund)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetRequestRefundDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetRequestRefundDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRequestRefundDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RequestRefundDetails
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RequestRefundDetails)
            End Get
        End Property
    End Class
End Namespace
