'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MBWayConnectedService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResultOperation", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResultOperation
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MBWayPaymentOperationResultField As MBWayConnectedService.MBWayPaymentOperationResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.ErrorDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescriptionField, value) <> true) Then
                    Me.ErrorDescriptionField = value
                    Me.RaisePropertyChanged("ErrorDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MBWayPaymentOperationResult() As MBWayConnectedService.MBWayPaymentOperationResult
            Get
                Return Me.MBWayPaymentOperationResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MBWayPaymentOperationResultField, value) <> true) Then
                    Me.MBWayPaymentOperationResultField = value
                    Me.RaisePropertyChanged("MBWayPaymentOperationResult")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MBWayPaymentOperationResult", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MBWayPaymentOperationResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDescriptionDetailField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperationId() As String
            Get
                Return Me.OperationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationIdField, value) <> true) Then
                    Me.OperationIdField = value
                    Me.RaisePropertyChanged("OperationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As String
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusCodeField, value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDescription() As String
            Get
                Return Me.StatusDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDescriptionField, value) <> true) Then
                    Me.StatusDescriptionField = value
                    Me.RaisePropertyChanged("StatusDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDescriptionDetail() As String
            Get
                Return Me.StatusDescriptionDetailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDescriptionDetailField, value) <> true) Then
                    Me.StatusDescriptionDetailField = value
                    Me.RaisePropertyChanged("StatusDescriptionDetail")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResultDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResultDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MBWayPaymentDetailsField As MBWayConnectedService.MBWayPaymentMerchant
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.ErrorDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescriptionField, value) <> true) Then
                    Me.ErrorDescriptionField = value
                    Me.RaisePropertyChanged("ErrorDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MBWayPaymentDetails() As MBWayConnectedService.MBWayPaymentMerchant
            Get
                Return Me.MBWayPaymentDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MBWayPaymentDetailsField, value) <> true) Then
                    Me.MBWayPaymentDetailsField = value
                    Me.RaisePropertyChanged("MBWayPaymentDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MBWayPaymentMerchant", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MBWayPaymentMerchant
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AmountField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDescriptionDetailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UpdateStatusDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidRequestField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Amount() As Decimal
            Get
                Return Me.AmountField
            End Get
            Set
                If (Me.AmountField.Equals(value) <> true) Then
                    Me.AmountField = value
                    Me.RaisePropertyChanged("Amount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CategoryId() As Integer
            Get
                Return Me.CategoryIdField
            End Get
            Set
                If (Me.CategoryIdField.Equals(value) <> true) Then
                    Me.CategoryIdField = value
                    Me.RaisePropertyChanged("CategoryId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperationId() As String
            Get
                Return Me.OperationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationIdField, value) <> true) Then
                    Me.OperationIdField = value
                    Me.RaisePropertyChanged("OperationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Phone() As String
            Get
                Return Me.PhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneField, value) <> true) Then
                    Me.PhoneField = value
                    Me.RaisePropertyChanged("Phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestDate() As System.Nullable(Of Date)
            Get
                Return Me.RequestDateField
            End Get
            Set
                If (Me.RequestDateField.Equals(value) <> true) Then
                    Me.RequestDateField = value
                    Me.RaisePropertyChanged("RequestDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As String
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusCodeField, value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDescription() As String
            Get
                Return Me.StatusDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDescriptionField, value) <> true) Then
                    Me.StatusDescriptionField = value
                    Me.RaisePropertyChanged("StatusDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDescriptionDetail() As String
            Get
                Return Me.StatusDescriptionDetailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDescriptionDetailField, value) <> true) Then
                    Me.StatusDescriptionDetailField = value
                    Me.RaisePropertyChanged("StatusDescriptionDetail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UpdateStatusDate() As System.Nullable(Of Date)
            Get
                Return Me.UpdateStatusDateField
            End Get
            Set
                If (Me.UpdateStatusDateField.Equals(value) <> true) Then
                    Me.UpdateStatusDateField = value
                    Me.RaisePropertyChanged("UpdateStatusDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidRequest() As Boolean
            Get
                Return Me.ValidRequestField
            End Get
            Set
                If (Me.ValidRequestField.Equals(value) <> true) Then
                    Me.ValidRequestField = value
                    Me.RaisePropertyChanged("ValidRequest")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResultRequestRefund", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResultRequestRefund
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.ErrorDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescriptionField, value) <> true) Then
                    Me.ErrorDescriptionField = value
                    Me.RaisePropertyChanged("ErrorDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestRefundDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Webservices.Core.Entiti"& _ 
        "es"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RequestRefundDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RefundDetailsField As MBWayConnectedService.MBWayRefundRequestMerchant
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.ErrorDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDescriptionField, value) <> true) Then
                    Me.ErrorDescriptionField = value
                    Me.RaisePropertyChanged("ErrorDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RefundDetails() As MBWayConnectedService.MBWayRefundRequestMerchant
            Get
                Return Me.RefundDetailsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RefundDetailsField, value) <> true) Then
                    Me.RefundDetailsField = value
                    Me.RaisePropertyChanged("RefundDetails")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MBWayRefundRequestMerchant", [Namespace]:="http://schemas.datacontract.org/2004/07/CompraFacil.MBWay.Entities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MBWayRefundRequestMerchant
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AmountField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CFEntityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CFMerchantIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessedDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDescriptionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Amount() As Decimal
            Get
                Return Me.AmountField
            End Get
            Set
                If (Me.AmountField.Equals(value) <> true) Then
                    Me.AmountField = value
                    Me.RaisePropertyChanged("Amount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CFEntity() As Integer
            Get
                Return Me.CFEntityField
            End Get
            Set
                If (Me.CFEntityField.Equals(value) <> true) Then
                    Me.CFEntityField = value
                    Me.RaisePropertyChanged("CFEntity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CFMerchantId() As String
            Get
                Return Me.CFMerchantIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CFMerchantIdField, value) <> true) Then
                    Me.CFMerchantIdField = value
                    Me.RaisePropertyChanged("CFMerchantId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClientEmail() As String
            Get
                Return Me.ClientEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientEmailField, value) <> true) Then
                    Me.ClientEmailField = value
                    Me.RaisePropertyChanged("ClientEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperationId() As String
            Get
                Return Me.OperationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationIdField, value) <> true) Then
                    Me.OperationIdField = value
                    Me.RaisePropertyChanged("OperationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Phone() As String
            Get
                Return Me.PhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneField, value) <> true) Then
                    Me.PhoneField = value
                    Me.RaisePropertyChanged("Phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProcessedDate() As System.Nullable(Of Date)
            Get
                Return Me.ProcessedDateField
            End Get
            Set
                If (Me.ProcessedDateField.Equals(value) <> true) Then
                    Me.ProcessedDateField = value
                    Me.RaisePropertyChanged("ProcessedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestDate() As System.Nullable(Of Date)
            Get
                Return Me.RequestDateField
            End Get
            Set
                If (Me.RequestDateField.Equals(value) <> true) Then
                    Me.RequestDateField = value
                    Me.RaisePropertyChanged("RequestDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Source() As String
            Get
                Return Me.SourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceField, value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDescription() As String
            Get
                Return Me.StatusDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDescriptionField, value) <> true) Then
                    Me.StatusDescriptionField = value
                    Me.RaisePropertyChanged("StatusDescription")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MBWayConnectedService.IMBWayWebServiceV2")>  _
    Public Interface IMBWayWebServiceV2
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/CreatePayment", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/CreatePaymentResponse")>  _
        Function CreatePayment(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal amount As Decimal, ByVal phone As String, ByVal description As String, ByVal clientEmail As String, ByVal clientVATNumber As String, ByVal clientExternalReference As String, ByVal clientName As String, ByVal categoryId As Integer, ByVal callBackURL As String) As MBWayConnectedService.ResultOperation
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/CreatePayment", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/CreatePaymentResponse")>  _
        Function CreatePaymentAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal amount As Decimal, ByVal phone As String, ByVal description As String, ByVal clientEmail As String, ByVal clientVATNumber As String, ByVal clientExternalReference As String, ByVal clientName As String, ByVal categoryId As Integer, ByVal callBackURL As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultOperation)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetailsResponse")>  _
        Function GetPaymentDetails(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.ResultDetails
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetails", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/GetPaymentDetailsResponse")>  _
        Function GetPaymentDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultDetails)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/RequestRefund", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/RequestRefundResponse")>  _
        Function RequestRefund(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.ResultRequestRefund
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/RequestRefund", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/RequestRefundResponse")>  _
        Function RequestRefundAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultRequestRefund)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetailsResponse")>  _
        Function GetRequestRefundDetails(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.RequestRefundDetails
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetails", ReplyAction:="http://tempuri.org/IMBWayWebServiceV2/GetRequestRefundDetailsResponse")>  _
        Function GetRequestRefundDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.RequestRefundDetails)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMBWayWebServiceV2Channel
        Inherits MBWayConnectedService.IMBWayWebServiceV2, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MBWayWebServiceV2Client
        Inherits System.ServiceModel.ClientBase(Of MBWayConnectedService.IMBWayWebServiceV2)
        Implements MBWayConnectedService.IMBWayWebServiceV2
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreatePayment(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal amount As Decimal, ByVal phone As String, ByVal description As String, ByVal clientEmail As String, ByVal clientVATNumber As String, ByVal clientExternalReference As String, ByVal clientName As String, ByVal categoryId As Integer, ByVal callBackURL As String) As MBWayConnectedService.ResultOperation Implements MBWayConnectedService.IMBWayWebServiceV2.CreatePayment
            Return MyBase.Channel.CreatePayment(cfMerchantId, password, cfEntityOrType, amount, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, callBackURL)
        End Function
        
        Public Function CreatePaymentAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal amount As Decimal, ByVal phone As String, ByVal description As String, ByVal clientEmail As String, ByVal clientVATNumber As String, ByVal clientExternalReference As String, ByVal clientName As String, ByVal categoryId As Integer, ByVal callBackURL As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultOperation) Implements MBWayConnectedService.IMBWayWebServiceV2.CreatePaymentAsync
            Return MyBase.Channel.CreatePaymentAsync(cfMerchantId, password, cfEntityOrType, amount, phone, description, clientEmail, clientVATNumber, clientExternalReference, clientName, categoryId, callBackURL)
        End Function
        
        Public Function GetPaymentDetails(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.ResultDetails Implements MBWayConnectedService.IMBWayWebServiceV2.GetPaymentDetails
            Return MyBase.Channel.GetPaymentDetails(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
        
        Public Function GetPaymentDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultDetails) Implements MBWayConnectedService.IMBWayWebServiceV2.GetPaymentDetailsAsync
            Return MyBase.Channel.GetPaymentDetailsAsync(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
        
        Public Function RequestRefund(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.ResultRequestRefund Implements MBWayConnectedService.IMBWayWebServiceV2.RequestRefund
            Return MyBase.Channel.RequestRefund(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
        
        Public Function RequestRefundAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.ResultRequestRefund) Implements MBWayConnectedService.IMBWayWebServiceV2.RequestRefundAsync
            Return MyBase.Channel.RequestRefundAsync(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
        
        Public Function GetRequestRefundDetails(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As MBWayConnectedService.RequestRefundDetails Implements MBWayConnectedService.IMBWayWebServiceV2.GetRequestRefundDetails
            Return MyBase.Channel.GetRequestRefundDetails(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
        
        Public Function GetRequestRefundDetailsAsync(ByVal cfMerchantId As String, ByVal password As String, ByVal cfEntityOrType As Integer, ByVal operationId As String) As System.Threading.Tasks.Task(Of MBWayConnectedService.RequestRefundDetails) Implements MBWayConnectedService.IMBWayWebServiceV2.GetRequestRefundDetailsAsync
            Return MyBase.Channel.GetRequestRefundDetailsAsync(cfMerchantId, password, cfEntityOrType, operationId)
        End Function
    End Class
End Namespace
